#!/usr/bin/env node
import { writeFileSync } from 'node:fs';

const apiKey = process.env.GOOGLE_API_KEY?.trim();
const model = process.env.GOOGLE_MODEL?.trim() || process.env.GEMMA_MODEL?.trim() || 'gemini-2.5-flash-lite';
const port = process.env.PORT?.trim() || '3000';

if (!apiKey) {
  console.error('GOOGLE_API_KEY 환경 변수를 먼저 설정한 뒤 실행하세요. 예: GOOGLE_API_KEY=your-key npm run setup:env');
  process.exit(1);
}

const envBody = [
  '# Generated by npm run setup:env. This file is ignored by Git.',
  `GOOGLE_API_KEY=${apiKey}`,
  `GOOGLE_MODEL=${model}`,
  `PORT=${port}`,
  '',
].join('\n');

writeFileSync('.env', envBody, { encoding: 'utf8', mode: 0o600 });
console.log('.env 파일을 생성했습니다. API 키는 Git에 커밋되지 않습니다.');
